name: Build
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: gwlb
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG